name: Build

env:
  MAVEN_OPTS: " -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN "
  MAVEN_CLI_SETTINGS: " -s .github/workflows/settings.xml "
  MAVEN_CLI_OPTS: " --show-version --batch-mode --no-transfer-progress "

on:
  push:
    paths:
      - 'conventional-commits-*/**'
      - 'pom.xml'
jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/net/videki/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests $MAVEN_OPTS $MAVEN_CLI_SETTINGS $MAVEN_CLI_OPTS

  test_job:
    name: Test
    runs-on: ubuntu-latest
    needs: build_job

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/net/videki/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test build
        run: mvn clean verify $MAVEN_OPTS $MAVEN_CLI_SETTINGS $MAVEN_CLI_OPTS

  release_job:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build_job
      - test_job
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Prepare release
        run: mvn release:prepare -Prelease -DskipTests $MAVEN_OPTS $MAVEN_CLI_SETTINGS $MAVEN_CLI_OPTS

      - name: Publish release
        run: mvn release:perform -Prelease -DskipTests $MAVEN_OPTS $MAVEN_CLI_SETTINGS $MAVEN_CLI_OPTS
