name: Coverage

env:
  MAVEN_OPTS: " -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN "
  MAVEN_CLI_SETTINGS: " -s .github/workflows/settings.xml "
  MAVEN_CLI_OPTS: " --show-version --batch-mode --no-transfer-progress "

on:
  push:
    paths:
      - 'conventional-commits-*/**'
      - 'pom.xml'

jobs:
  coverage_job:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/net/videki/**
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean verify -Pcoverage $MAVEN_OPTS $MAVEN_CLI_SETTINGS $MAVEN_CLI_OPTS

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        name: conventional-commits-for-java

    - name: Codecov upload
      run: bash <(curl -s https://codecov.io/bash)
