name: Test

env:
  MAVEN_OPTS: " -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN "
  MAVEN_CLI_OPTS: " --show-version --batch-mode --no-transfer-progress "

on:
  push:
    paths:
      - 'conventional-commits-*/**'
      - 'pom.xml'
jobs:
  test_job:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/net/videki/**
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test build
        run: mvn clean verify $MAVEN_OPTS $MAVEN_CLI_OPTS
